### ISSUE TITLE
red+blue=purple?

### ISSUE THREAD

**Issue by saiedg** [rvanwijnen/spectral.js#2]
<img width="909" alt="Screenshot 2023-04-12 at 6 51 24 AM" src="https://user-images.githubusercontent.com/1972987/231363519-88aef357-441a-4ef6-a5fa-9068cff6a75e.png">

<img width="851" alt="Screenshot 2023-04-12 at 6 54 20 AM" src="https://user-images.githubusercontent.com/1972987/231363790-c440b925-ee9e-4238-be1b-cf899e0ec9a6.png">

<img width="874" alt="Screenshot 2023-04-12 at 6 56 32 AM" src="https://user-images.githubusercontent.com/1972987/231364309-ee1b549d-de62-472f-9b4b-4949bf05dc14.png">

In these three cases, it appears that RGB is more correct than the spectral. 
Red + yellow = orange 
red + blue = purple
Red + white = pink

**Comment by rvanwijnen** [comment]
That's one of the quirks of Spectral.js.

Spectral.js tries to emulate the full spectrum but only has 3 channels for the mixing, red, green and blue.
There is just too little data for a fully accurate representation of the full spectrum.

This is something you have to account for in your design decisions.

The accuracy could improve with better data sets or increasing the channels, which I'm researching now.

Spectral.js is not magic but it does a decent job at what it's intended for.

Please feel free to give your opinion.

**Comment by rvanwijnen** [comment]
You could just use linear RGB mixing for purple.
It's a something you have to implement as a designer/artist.
Spectral.js will not provide this functionality.

But to do Spectral.js justice I would like to elaborate on the 'blue + red = purple'.
Although paint mixing is subtractive mixing in practice it doesn't really work that way.
In pigment mixing blue mixed with red makes a brownish color.

![image](https://user-images.githubusercontent.com/129797337/231476481-f2f85acb-2134-45f4-ab33-77ee129ebcda.png)

You can find some more info on pigment mixing here: https://drawandpaintforfun.com/how-to-mix-purple/2/

You could use magenta to get a purplish color.

There is a lot that can be improved on Spectral.js, but it is pretty accurate.
