### ISSUE TITLE
Issues in the examples

### ISSUE THREAD

**Issue by rjsworking** [rvanwijnen/spectral.js#4]
Hi, thank you very much for this amazing library

There's an issue in the examples and probably in the code too

```
let palette = spectral.palette('#00357B', '#F0F0F0', `9);
let palette = spectral.palette('rgb(240, 240, 240)', 'rgb(240, 240, 240)', 9);
let palette = spectral.palette('[240, 240, 240]', '[240, 240, 240]', 9, spectral.RGB);
```

I guess it should be:

```
let palette = spectral.palette('#00357B', '#F0F0F0', `9);
let palette = spectral.palette('rgb(0, 53, 123)', 'rgb(240, 240, 240)', 9);
let palette = spectral.palette([0, 53, 123], [240, 240, 240], 9, spectral.RGB);
```

The result doesn't seem to be correct either.

```
palette = spectral.palette('#00357B', '#F0F0F0', 6);
console.log('PALETTE 1 ', palette)  // ['#00357b', '#01509c', '#288aca', '#67bee3', '#b1e2ee', '#f0f0f0']

--> palette = spectral.palette('rgb(0,53,123)', 'rgb(240,240,240)', 6);
--> console.log('PALETTE 2 ', palette)  // ['#NaNNaNNaN', '#NaNNaNNaN', '#NaNNaNNaN', '#NaNNaNNaN', '#NaNNaNNaN', '#NaNNaNNaN']

palette = spectral.palette([0, 53, 123], [240, 240, 240], 6);
console.log('PALETTE 3 ', palette)  // ['#00357b', '#01509c', '#288aca', '#67bee3', '#b1e2ee', '#f0f0f0']
```

Is it a issue in the example or a bug in mix() function in the for loop `for ( let i = 0; i < SIZE; i++ ) ..`. ?

Cheers
rjs

**Comment by rvanwijnen** [comment]
You are right! The ‘rgb()’ probably isn’t parsed as it should. I will look at this as soon as I can.

**Comment by rvanwijnen** [comment]
Hi! I've updated the library to v2.0.1, the color string parsing is fixed in this release.
I've also fixed the errors in the readme.

Thank you for pointing out the errors.

I will close this issue.
If there is still a problem or you found a new problem please open an new issue.

**Comment by rvanwijnen** [comment]
Hi! I've updated the library to v2.0.1, the color string parsing is fixed in this release.
I've also fixed the errors in the readme.

Thank you for pointing out the errors.

I will close this issue.
If there is still a problem or you found a new problem please open an new issue.

**Comment by rjsworking** [comment]
Hi. You're welcome. It's working as expected. 

Cheers
rjs
