### ISSUE TITLE
Does spectral.glsl take transparancy into account?

### ISSUE THREAD

**Issue by mheesakkers** [rvanwijnen/spectral.js#5]
Hi Richard!

Very nice library, I'm dabbling around with it in GLSL & p5.js and I think I came accross a bug. If not, it's possibly my lack of knowledge in shaders ;)

I'm mixing two textures who are both transparant with some colored shapes on top of it. The provided textures uses anti-aliasing but when I'm mixing the colors I get a result that is not anti-aliased. I suspect that the color mixing produces fully opague colors. Could this be so?

**Input vs output**
![Input](https://github.com/rvanwijnen/spectral.js/assets/5702106/26bed87e-b209-4dc5-b860-5f990b557623)
![Output](https://github.com/rvanwijnen/spectral.js/assets/5702106/c5819111-6a40-46ed-83e3-8458526a0772)

**p5.js Sketch**
https://editor.p5js.org/Misha.studio/sketches/8H7gCSjxb

**Comment by mheesakkers** [comment]
I don't think it was a bug but my own lack of knowledge in WebGL. I think I've got a color mixing shader working right now which used alpha blending & proper mixing of anti aliasing.

**Link to working sketch**
https://editor.p5js.org/Misha.studio/sketches/-A_R3fKR8

**Comment by rvanwijnen** [comment]
I was about to make a lengthy post about webgl and alpha transparency but you've figured it out yourself!

Glad you like spectral.js!

Ronald.

**Comment by mheesakkers** [comment]
Sorry for the name mismatch 😅
