### ISSUE TITLE
GLSL mix occasional invalid step

### ISSUE THREAD

**Issue by kellymilligan** [rvanwijnen/spectral.js#9]
Hey, loving the library. 

I'm using the glsl mix function, and when mixing with full channel color values (e.g. yellow `vec3(1., 1., 0.)`), and especially black or white (`vec3(0.)`, `vec3(1.)`) I'm sometimes getting a few steps of invalid color calculation that seems to create black banding near the end of the mix. Here are a few examples:

![download (3)](https://github.com/rvanwijnen/spectral.js/assets/6025493/2ee3518b-1b5d-46cf-a574-822bc836c9aa)
![download (2)](https://github.com/rvanwijnen/spectral.js/assets/6025493/81a7f711-2d3f-4ed5-a9d7-cd69cde4f559)
![download (1)](https://github.com/rvanwijnen/spectral.js/assets/6025493/fa62a38f-42aa-45ef-ae4f-9102211a40d2)
![download](https://github.com/rvanwijnen/spectral.js/assets/6025493/7b4e9574-56aa-4bee-a34a-6a25aaf4520f)

Here's an easy reproduction example:
```
vec4 color = vec4(0., 0., 0., 1.);
color.xyz += spectral_mix(vec3(0.), vec3(1.), uv.x);
```
![image](https://github.com/rvanwijnen/spectral.js/assets/6025493/a2c860f5-dab6-4fed-a0c7-d9a8dc2e370a)

I can get around this by using slightly off color values:
```
color.xyz += spectral_mix(vec3(0.01), vec3(0.99), uv.x);
```
![image](https://github.com/rvanwijnen/spectral.js/assets/6025493/a452f435-d873-4741-a479-db8557817376)

Cheers!

**Comment by rvanwijnen** [comment]
Hi Kelly! Are you using WebGL 1 by any chance? There are some precision errors with WebGL 1. If you are able to it’s better to use WebGL 2 as float values have more precision.
I myself have experienced the same problems with WebGL 1.

**Comment by kellymilligan** [comment]
Hey! Thanks. 

Using WebGL2 in this case, and using `precision highp float;` 👍 

Cheers

**Comment by rvanwijnen** [comment]
Awesome! I will close this issue.

Hit me up on twitter, I’d like to see what you’re creating with it.
